### ISSUE TITLE
what example is expected to do ?

### ISSUE THREAD

**Issue by avilleret** [bakercp/ofxSerial#9]
There is no description of what `example_buffered_serial_device` does.
out-of-the-box, it doesn't do anything very exciting... (I'm at https://github.com/bakercp/ofxSerial/commit/8280052b62ad593e3f89e5228327d6be715d6823)
but after un-commeting line https://github.com/bakercp/ofxSerial/blob/master/example_buffered_serial_device/src/ofApp.cpp#L145
it does something more interessant :-)

**Comment by bakercp** [comment]
Oops.  That shouldn't have been committed.  It was an experiment for an unrelated project.  I'll revert back to the original example shortly.

**Comment by bakercp** [comment]
Fixed with 5ded59c926b333e5d18f30e5d68952422f1e4494 

Apologies.  Basically it is an example of buffered serial -- it gives you serial events whenever there is a new serial "packet", that is whenever it gets a packet boundary marker like a new line (or some other marker that you choose).

**Comment by avilleret** [comment]
Thanks for the quick fix.
Btw, I understood what the example does by reading the code, but you might add a small description in the code (basically what you wrote here) to help others.

**Comment by bakercp** [comment]
Yeah, it's on my todo list ... to document the package more thoroughly in
the future.  For now, since I have so many addons to maintain I'm trying to
keep my examples short, clear and concise.  Thanks for the report and
suggestions!  Also feel free to issue a pull request if you want to add any
documentation :)


---
http://christopherbaker.net
